### ISSUE TITLE
Packages aren't compatible with GenerateSwiftServer 

### ISSUE THREAD

**Issue by tfrank64** [IBM-Swift/GeneratedSwiftServer-CloudantStore#3]
The GenerateSwiftServer project is using a specific version of Kitura (1.1.x) while this repo is just using 1.x.x which has caused a dependency graph issue. I made a change to fix this in my fork and I can pull request if you want: https://github.com/tfrank64/GeneratedSwiftServer-CloudantStore/blob/master/Package.swift

**Comment by tunniclm** [comment]
This is an interesting point, we need to be consistent about which version we fix (major/minor/patch). It seems reasonable to fix the minor version everywhere so we can do controlled upgrades to new bring on new function.

We should probably update the dependency on GeneratedSwiftServer to 0.1 as well, since it is in development and we will be making breaking changes on minor version updates until we hit 1.0.
